### ISSUE TITLE
More friendly name

### ISSUE THREAD

**Issue by gordcorp** [siemens/sentry-auth-oidc#10]
I am trying to use this auth provider with Azure AD. Azure seems to give each tenant their own domain and issuer url, i.e. I'm using an OIDC_DOMAIN of `https://login.microsoftonline.com/<tenancy-id>/v2.0`, where <tenancy-id> is a uuid. 

Users see this screen when they try to login with sso:
![59985361-8dbf2d80-9674-11e9-9957-9defe708e256](https://user-images.githubusercontent.com/2324569/59995302-1b614400-969a-11e9-99b0-429da2055fad.png)

I cant see anything more user friendly in the openid-configuration response to use as the name,  e.g. see `curl https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration | jq .`

Any thoughts on adding an (optional?) env var configuration like `OIDC_NAME` to use as the name?

**Comment by max-wittig** [comment]
I guess we could use the existing `OIDC_ISSUER` for this. I will look into it.

**Comment by gordcorp** [comment]
Oh yeah that'd be fine, I didnt realise that wasnt used anywhere else. So if I specify all those values (but not OIDC_DOMAIN)  instead of relying on `openid-configuration`, I can then put something nicer into OIDC_ISSUER. That should work for me.
