### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by AienTech** [siemens/sentry-auth-oidc#16]
Could you please provide an installation guide on the on-premise version, using docker-compose?

it seems that the sentry doesn't recommend using `sentry.conf.py` anymore, therefore the configurations should be put on `config.yml`.

it would be awesome to have an installation guide.

many thanks

**Comment by bufferoverflow** [comment]
You can set the environment variables within docker-compose and add the following to `sentry.conf.py`

```python
if 'OIDC_CLIENT_ID' in os.environ:
    OIDC_CLIENT_ID = env('OIDC_CLIENT_ID')
    OIDC_CLIENT_SECRET = env('OIDC_CLIENT_SECRET')
    OIDC_SCOPE = env('OIDC_SCOPE')
    OIDC_DOMAIN = env('OIDC_DOMAIN')
    OIDC_ISSUER = env('OIDC_ISSUER')
```

I've not investigated on `config.yml` until now.

**Comment by max-wittig** [comment]
Actually only the variables are needed in `sentry.conf.py`.

```
OIDC_CLIENT_ID = ""

OIDC_CLIENT_SECRET = ""

OIDC_SCOPE = "openid email"

OIDC_DOMAIN = "https://accounts.google.com"  # e.g. for Google
```

I also haven't looked into their custom config file. The `sentry.conf.py` is a normal django settings file and can still be used.

**Comment by AienTech** [comment]
nice! it's sad that it hasn't been documented on the sentry website (maybe I haven't noticed that)...

thanks for the help
