### ISSUE TITLE
got error with self-hosted sentry

### ISSUE THREAD

**Issue by lucifan** [siemens/sentry-auth-oidc#35]
Hey, I tried to apply this provider in my self-hosted sentry, following this guide https://develop.sentry.dev/self-hosted/

Simply added `pip install sentry-auth-oidc` in `enhance-image.sh` and ran `./install.sh`, but it failed and I got error as follows：

```
  File "/usr/local/lib/python3.8/site-packages/oidc/apps.py", line 10, in ready
    from .provider import OIDCProvider
  File "/usr/local/lib/python3.8/site-packages/oidc/provider.py", line 17, in <module>
    from .views import FetchUser, OIDCConfigureView
  File "/usr/local/lib/python3.8/site-packages/oidc/views.py", line 5, in <module>
    from sentry.utils.compat import map
ImportError: cannot import name 'map' from 'sentry.utils.compat' (/usr/local/lib/python3.8/site-packages/sentry/utils/compat/__init__.py)
An error occurred, caught SIGERR on line 13
```

I wonder if was cause by the mismatch of sentry version, or maybe i did something wrong with these steps, any clues?

**Comment by max-wittig** [comment]
Hi. Thanks for creating an issue!

I think the latest Sentry version changed some things. We're looking into it already, as we also want to update to 20.8 soon. 

We keep you updated here

/cc @dlouzan

**Comment by dlouzan** [comment]
@lucifan Thanks for the heads-up, it's good to know we are not the only users 😆 We started some work already in #33 and we should be ready in the next days.
