### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by akloster** [siemens/sentry-auth-oidc#38]
I tried to follow the installation instructions. For one thing it now should say to add "pip install sentry-auth-oidc" to "sentry/enhance-image.sh".

I also added some configuration settings to the bottom of sentry.conf beginning with "OIDC_". I'm trying to integrate with keycloak, by the way.

I verified that pip installs the package and that the conf is loaded, but I see no sign of the plugin doing anything. There is no error or any mention in the logs. There is no second login option in the login screen and I didn't find anything in the options.

Any idea what I might have done wrong? Am I missing something obvious?

**Comment by max-wittig** [comment]
Do you see the image on `https://your-instance.com/manage/status/packages/`?

![image](https://user-images.githubusercontent.com/6639323/215846189-e6b2843c-ff7e-49c1-894a-464a5ec70526.png)

**Comment by akloster** [comment]
Sorry, for the inconvenience and thank you for your reply.

I missed something indeed very obvious and stupid: I didn't rename enhance-image.example.sh to enhance-image.sh ....
