### ISSUE TITLE
On Premise 24.2.0 Error

### ISSUE THREAD

**Issue by riegerben** [siemens/sentry-auth-oidc#47]
After pip installing sentry-auth-oidc==8.1.0, I'm getting the error: 

ImportError: cannot import name 'map' from 'sentry.utils.compat' (/usr/local/lib/python3.11/site-packages/sentry/utils/compat/__init__.py)

**Comment by riegerben** [comment]
Fixed by downgrading to sentry-auth-oidc 8.0.0

**Comment by max-wittig** [comment]
Hi! @riegerben. Yes we keep sentry-auth-oidc compatible with the latest Sentry version, without downwards compatibility.

Maybe we should specify that in the readme.
